---
title: "Untitled"
author: "Fensals"
date: "6/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

#Necessary Libraries

library(rvest)
library(tidyverse)
library(readxl)
library(dplyr)
```


```{r}
#Assigning a variable name to the URL to be scraped  
link <-  ('https://www.eventbrite.com/d/united-states/free--food-and-drink--games/?page=1')

#Extracting the HTML content of the URL   
webpage <-  read_html(link)


# Extracting required elements from the HTML Content

Title <-  webpage %>% html_nodes("div.eds-structure.eds-structure--min-height div.eds-structure__body div.eds-structure__main-mask div.eds-structure__fixed-bottom-bar-layout-wrapper div.eds-fixed-bottom-bar-layout div.eds-fixed-bottom-bar-layout__content div.eds-structure__main-container main.eds-structure__main div.feed-search-page div.search-base-screen__root section.search-base-screen__search-panel div.search-results-panel-content div.search-main-content ul.search-main-content__events-list:nth-child(1) div.search-event-card-wrapper div.search-event-card-rectangle-image div.search-event-card.eds-l-mar-vert-1 div.eds-event-card--consumer div.eds-card.eds-card--neutral article.eds-l-pad-all-4.eds-event-card-content.eds-event-card-content--list.eds-event-card-content--standard.eds-event-card-content--fixed div.eds-event-card-content__content-container.eds-l-pad-right-4 div.eds-event-card-content__content div.eds-event-card-content__content__principal div.eds-event-card-content__primary-content a.eds-event-card-content__action-link h3.eds-event-card-content__title.eds-text-color--ui-800.eds-text-bl.eds-text-weight--heavy div:nth-child(1) > div.eds-event-card__formatted-name--is-clamped.eds-event-card__formatted-name--is-clamped-three.eds-text-weight--heavy") %>% html_text()

Address <-  webpage %>% html_nodes("div.eds-structure.eds-structure--min-height div.eds-structure__body div.eds-structure__main-mask div.eds-structure__fixed-bottom-bar-layout-wrapper div.eds-fixed-bottom-bar-layout div.eds-fixed-bottom-bar-layout__content div.eds-structure__main-container main.eds-structure__main div.feed-search-page div.search-base-screen__root section.search-base-screen__search-panel div.search-results-panel-content div.search-main-content ul.search-main-content__events-list:nth-child(1) div.search-event-card-wrapper div.search-event-card-square-image div.search-event-card.eds-l-mar-vert-1 div.eds-event-card--consumer div.eds-card.eds-card--neutral article.eds-l-pad-all-4.eds-event-card-content.eds-event-card-content--list.eds-event-card-content--mini.eds-event-card-content--square div.eds-event-card-content__content-container.eds-l-pad-right-4 div.eds-event-card-content__content div.eds-event-card-content__content__principal div.eds-event-card-content__sub-content div.eds-event-card-content__sub.eds-text-bm.eds-text-color--ui-600.eds-l-mar-top-1.eds-event-card-content__sub--cropped > div.card-text--truncated__one") %>% html_text()


Date <- webpage %>% html_nodes(" div.eds-structure.eds-structure--min-height div.eds-structure__body div.eds-structure__main-mask div.eds-structure__fixed-bottom-bar-layout-wrapper div.eds-fixed-bottom-bar-layout div.eds-fixed-bottom-bar-layout__content div.eds-structure__main-container main.eds-structure__main div.feed-search-page div.search-base-screen__root section.search-base-screen__search-panel div.search-results-panel-content div.search-main-content ul.search-main-content__events-list:nth-child(1) div.search-event-card-wrapper div.search-event-card-rectangle-image div.search-event-card.eds-l-mar-vert-1 div.eds-event-card--consumer div.eds-card.eds-card--neutral article.eds-l-pad-all-4.eds-event-card-content.eds-event-card-content--list.eds-event-card-content--standard.eds-event-card-content--fixed div.eds-event-card-content__content-container.eds-l-pad-right-4 div.eds-event-card-content__content div.eds-event-card-content__content__principal div.eds-event-card-content__primary-content > div.eds-evet-card-content__sub-title.eds-text-color--ui-orange.eds-l-pad-bot-1.eds-l-pad-top-2.eds-text-weight--heavy.eds-text-bm") %>% html_text()
    
Link <-  webpage %>% html_nodes("div.eds-structure.eds-structure--min-height div.eds-structure__body div.eds-structure__main-mask   div.eds-structure__fixed-bottom-bar-layout-wrapper div.eds-fixed-bottom-bar-layout div.eds-fixed-bottom-bar-layout__content div.eds-structure__main-container main.eds-structure__main div.feed-search-page div.search-base-screen__root section.search-base-screen__search-panel div.search-results-panel-content div.search-main-content ul.search-main-content__events-list:nth-child(1) div.search-event-card-wrapper div.search-event-card-rectangle-image div.search-event-card.eds-l-mar-vert-1 div.eds-event-card--consumer div.eds-card.eds-card--neutral article.eds-l-pad-all-4.eds-event-card-content.eds-event-card-content--list.eds-event-card-content--standard.eds-event-card-content--fixed div.eds-event-card-content__content-container.eds-l-pad-right-4 div.eds-event-card-content__content div.eds-event-card-content__content__principal div.eds-event-card-content__primary-content > a.eds-event-card-content__action-link") %>%html_attr("href") %>% paste0()

 
Category <- webpage %>% html_nodes(".eds-l-pad-right-6+ .filter-panel__drawers__item .filter-panel__drawers__item__header--active") %>%html_text() 

Format <- webpage %>% html_nodes(".filter-panel__drawers__item:nth-child(8) .filter-panel__drawers__item__header--active") %>% html_text()

Country <-  link %>%
              str_split(pattern = '/')%>%
              map_chr(5)
  
Timestamp <- Sys.time()


Page_No <-  link %>% 
              str_split(pattern = '/')%>%
              map_chr(7)%>% 
              str_split(pattern = '=')%>% 
              map_chr(2)

#combining all columns into a dataframe
Event <-  data.frame(Timestamp, Link, Title, Address, Date, Category, Format, Country, Page_No, stringsAsFactors = FALSE)


write.csv(Event,"EventTribe.csv", row.names = TRUE) #To export dataframe into a CSV file.
```


```{r}
web <- read_html(link)
Page_result <- web %>% html_nodes('.eds-l-mar-hor-3') %>% html_text()

No_of_Pages <- gsub("1 of ","",Page_result)%>% as.numeric()
```


```{r}
No_of_Pages
```


```{r}
seq(No_of_Pages)
```





